### PR TITLE
Simple supports clause in import

### LINKED ISSUE #1967: supports() clause doesn't support declaration-syntax
`supports()` clause support, that was introduced in 3.4.20 is not fully compatible with W3C CSS spec.

According to [CSS Cascading and Inheritance Level 4](https://www.w3.org/TR/2015/WD-css-cascade-4-20150908/#typedef-supports-condition) it's allowed to place `supports_conditions` **OR** `declaration` inside `supports()` clause.

```
@import [ <url> | <string> ]
        [ supports( [ <supports-condition> | <declaration> ] ) ]?
        <media-query-list>? ;
```

So the following imports are both valid and  equivalent:

``` css
@import "mystyle.css" supports(display: flex);
@import "mystyle.css" supports((display: flex));
```

However Sass compiler doesn't work for the following code:

``` scss
@import "mystyle.css" supports(display: flex);
```

And produces the following error:

```
Error: Invalid CSS after "....css" supports(": expected ")", was "display: flex);"
        on line 1 of test.scss
```

### PR DESCRIPTION
**Pull request by chriseppstein**
Specs are in https://github.com/sass/sass-spec/tree/import-supports/spec/sass_3_4_x/simple_supports_clause_in_import

This change fixes #1967.

### CODE REVIEW

File: lib/sass/scss/parser.rb [hunk 1]
```diff
@@ -589,6 +593,14 @@ def supports_operator
         cond
       end
 
+      def supports_declaration
+          return if tok?(/\(/)
+          name = sass_script(:parse)
+          tok!(/:/); ss
+          value = sass_script(:parse)
+          Sass::Supports::Declaration.new(name, value)
```
Comment (nex3) [inline lib/sass/scss/parser.rb:600]: Now that this is factored out, can you re-use it in `supports_condition_in_parens`?

**Comment by nex3** [comment]
:+1: as long as Travis succeeds!
